### ISSUE TITLE
How would I go about adding ranges to expressions?

### ISSUE THREAD

**Issue by lunacookies** [ebkalderon/example-fault-tolerant-parser#1]
Hi,

I’m working on making a parser for Rust, for the purpose of syntax highlighting. I’ve done a little bit of parsing with Nom 5.0 before, but it’s never had to be fault-tolerant. I had no idea how to achieve this, so I read your blog post.

The syntax highlighting API I’m working with requires a highlighter to take a `&str` as input, and emit a `Vec` of `HighlightedSpan`s, which look something like this:

```rust
struct HighlightedSpan<'text> {
    text: &'text str,
    group: Option<HighlightGroup>,
}
```

and where `HighlightGroup` is a massive enum of all the possible highlight groups a `HighlightedSpan` can have:

```rust
enum HighlightGroup {
    Keyword,
    Type,
    Error,
    // etc
}
```

I thought it would be a good first step to modify the code from your article to record the range of each `Expr`. (Of course, syntax highlighting requires a pretty different parser to that of a language server, so I also intend to remove error message support.) I’ve tried to do this (add ranges), but it doesn’t produce correct ranges for parenthesised expressions (the outer range is incorrect, not the range of the contained expression). I feel the code is quite messy now too, so I was wondering if you could take a stab at this issue.

It’s probably better to start again, rather than adapt what I’ve hacked together.

```rust
use std::cell::RefCell;
use std::ops::Range;

use nom::branch::alt;
use nom::bytes::complete::{take, take_till1, take_while};
use nom::character::complete::{anychar, char};
use nom::combinator::{all_consuming, map, not, recognize, rest, verify};
use nom::sequence::{delimited, preceded, terminated};

type LocatedSpan<'a> = nom_locate::LocatedSpan<&'a str, State<'a>>;
type IResult<'a, T> = nom::IResult<LocatedSpan<'a>, T>;

trait ToRange {
    fn to_range(&self) -> Range<usize>;
}

impl<'a> ToRange for LocatedSpan<'a> {
    fn to_range(&self) -> Range<usize> {
        let start = self.location_offset();
        let end = start + self.fragment().len();
        start..end
    }
}

#[derive(Debug)]
struct Error(Range<usize>, String);

#[derive(Clone, Debug)]
struct State<'a>(&'a RefCell<Vec<Error>>);

impl<'a> State<'a> {
    pub fn report_error(&self, error: Error) {
        self.0.borrow_mut().push(error);
    }
}

fn expect<'a, F, E, T>(parser: F, error_msg: E) -> impl Fn(LocatedSpan<'a>) -> IResult<Option<T>>
where
    F: Fn(LocatedSpan<'a>) -> IResult<T>,
    E: ToString,
{
    move |input| match parser(input) {
        Ok((remaining, out)) => Ok((remaining, Some(out))),
        Err(nom::Err::Error((input, _))) | Err(nom::Err::Failure((input, _))) => {
            let err = Error(input.to_range(), error_msg.to_string());
            input.extra.report_error(err);
            Ok((input, None))
        }
        Err(err) => Err(err),
    }
}

#[derive(Debug)]
enum ExprKind {
    Ident(String),
    Paren(Box<Expr>),
    Error,
}

#[derive(Debug)]
struct Expr {
    kind: ExprKind,
    range: Range<usize>,
}

fn ident(input: LocatedSpan) -> IResult<Expr> {
    let first = verify(anychar, |c| c.is_ascii_alphabetic() || *c == '_');
    let rest = take_while(|c: char| c.is_ascii_alphanumeric() || "_-'".contains(c));
    let ident = recognize(preceded(first, rest));

    map(ident, |span: LocatedSpan| Expr {
        kind: ExprKind::Ident(span.fragment().to_string()),
        range: span.to_range(),
    })(input)
}

fn paren(input: LocatedSpan) -> IResult<Expr> {
    let paren = delimited(
        char('('),
        expect(expr, "expected expression after `(`"),
        expect(char(')'), "missing `)`"),
    );

    let (span, expr) = paren(input)?;

    Ok((
        span.clone(),
        Expr {
            kind: ExprKind::Paren(Box::new(expr.unwrap_or(Expr {
                kind: ExprKind::Error,
                range: span.to_range(),
            }))),
            range: span.to_range(),
        },
    ))
}

fn error(input: LocatedSpan) -> IResult<Expr> {
    map(take_till1(|c| c == ')'), |span: LocatedSpan| {
        let err = Error(span.to_range(), format!("unexpected `{}`", span.fragment()));
        span.extra.report_error(err);

        Expr {
            kind: ExprKind::Error,
            range: span.to_range(),
        }
    })(input)
}

fn expr(input: LocatedSpan) -> IResult<Expr> {
    alt((paren, ident, error))(input)
}

fn source_file(input: LocatedSpan) -> IResult<Expr> {
    let expr = alt((
        expr,
        map(take(0usize), |_| Expr {
            kind: ExprKind::Error,
            range: todo!(), // not sure what could go here
        }),
    ));
    terminated(expr, preceded(expect(not(anychar), "expected EOF"), rest))(input)
}

fn parse(source: &str) -> Expr {
    let errors = RefCell::new(Vec::new());
    let input = LocatedSpan::new_extra(source, State(&errors));
    let (_, expr) = all_consuming(source_file)(input).expect("parser cannot fail");
    expr
}

fn main() {
    for input in &["foo", "(foo)", "(foo))", "(%", "(", "%", "()", ""] {
        println!("{:7} {:?}", input, parse(input));
    }
}
```

Thanks :)

**Comment by ebkalderon** [comment]
Hey, thanks for the kind words! I'm glad you found the blog post useful to you. 😊

It is much more difficult to get ranges for the successfully parsed expressions when the input type is character-based rather than token based, since tokens typically retain span information within them and don't require any extra work to calculate them at parse time. For that reason, I would strongly recommend using a custom type in place of `LocatedSpan` for a non-trivial parser project. But for the sake of example, here's one possible way to get the above example to work.

The `span` in the `let (span, expr) = paren(input)?` is _not_ the span of the expression. It is the span of the remaining text that has yet to be processed by `nom`. Using it as the value for `Expr::range` would be incorrect. Let's rename it to something more appropriate like `remaining` to make this clearer. The correct range for `ExprKind::Paren` is from `input.start..remaining.start`, and the correct range for the inner `ExprKind::Error` is `(input.start + 1)..(remaining.start - 0 || 1)`, depending on whether we successfully parsed the close parentheses without error.

```rust
fn paren(input: LocatedSpan) -> IResult<Expr> {
    // Rather than drop the close parentheses after we've parsed it using `delimited`,
    // we retain it instead, as shown below. Its type is `Option<LocatedSpan>`, and it
    // is used to help with the span calculation later on.
    let paren = preceded(
        char('('),
        pair(
            expect(expr, "expected expression after `(`"),
            expect(char(')'), "missing `)`"),
        ),
    );

    let i = input.clone();
    let (remaining, (expr, close_paren)) = paren(i)?;

    Ok((
        remaining.clone(),
        Expr {
            kind: ExprKind::Paren(Box::new(expr.unwrap_or_else(|| {
                let start = input.to_range().start + 1;
                let end = remaining.to_range().start - close_paren.map(|_| 1).unwrap_or(0);
                Expr {
                    kind: ExprKind::Error,
                    range: start..end,
                }
            }))),
            range: input.to_range().start..remaining.to_range().start,
        },
    ))
}
```

In regards to the `todo!()` you placed for the `take(0usize)` error, the correct value is always `0..0`. This is because, when given this expression:

```rust
alt((
    expr,
    map(take(0usize), |_| Expr {
        kind: ExprKind::Error,
        range: 0..0,
    }),
))
```

The only way for the `expr()` parser to fail above is if the input string is `""`, meaning that the fallback error range must always be `0..0`.

As a result of the above changes, I can get the following outputs from the parser example:

```text
foo     Expr { kind: Ident("foo"), range: 0..3 }
(foo)   Expr { kind: Paren(Expr { kind: Ident("foo"), range: 1..4 }), range: 0..5 }
(foo))  Expr { kind: Paren(Expr { kind: Ident("foo"), range: 1..4 }), range: 0..5 }
(%      Expr { kind: Paren(Expr { kind: Error, range: 1..2 }), range: 0..2 }
(       Expr { kind: Paren(Expr { kind: Error, range: 1..1 }), range: 0..1 }
%       Expr { kind: Error, range: 0..1 }
()      Expr { kind: Paren(Expr { kind: Error, range: 1..1 }), range: 0..2 }
        Expr { kind: Error, range: 0..0 }
```

Hope my responses helped in some way! Did I answer all your questions?

**Comment by lunacookies** [comment]
> Hey, thanks for the kind words! I'm glad you found the blog post useful to you. 😊

You’re very welcome :) Thanks for the detailed reply btw, I really appreciate it.

> It is much more difficult to get ranges for the successfully parsed expressions when the input type is character-based rather than token based, since tokens typically retain span information within them and don't require any extra work to calculate them at parse time. For that reason, I would strongly recommend using a custom type in place of `LocatedSpan` for a non-trivial parser project.

So are you saying that `LocatedSpan` is character-based? When you say that you would recommend a token-based input type, would that mean lexing the input first, before passing it into the parser? If so, would you say that this is worth it for syntax highlighting, or, since lexing covers the majority of work a syntax highlighter has to do, it would be mostly unnecessary?

> But for the sake of example, here's one possible way to get the above example to work.
> 
> The `span` in the `let (span, expr) = paren(input)?` is _not_ the span of the expression. It is the span of the remaining text that has yet to be processed by `nom`. Using it as the value for `Expr::range` would be incorrect.

Ah, that makes a lot of sense! Embarrassed that I forgot about that 😬

> Let's rename it to something more appropriate like `remaining` to make this clearer. The correct range for `ExprKind::Paren` is from `input.start..remaining.start`, and the correct range for the inner `ExprKind::Error` is `(input.start + 1)..(remaining.start - 0 || 1)`, depending on whether we successfully parsed the close parentheses without error.
> 
> ```rust
> fn paren(input: LocatedSpan) -> IResult<Expr> {
>     // Rather than drop the close parentheses after we've parsed it using `delimited`,
>     // we retain it instead, as shown below. Its type is `Option<LocatedSpan>`, and it
>     // is used to help with the span calculation later on.
>     let paren = preceded(
>         char('('),
>         pair(
>             expect(expr, "expected expression after `(`"),
>             expect(char(')'), "missing `)`"),
>         ),
>     );
> 
>     let i = input.clone();
>     let (remaining, (expr, close_paren)) = paren(i)?;
> 
>     Ok((
>         remaining.clone(),
>         Expr {
>             kind: ExprKind::Paren(Box::new(expr.unwrap_or_else(|| {
>                 let start = input.to_range().start + 1;
>                 let end = remaining.to_range().start - close_paren.map(|_| 1).unwrap_or(0);
>                 Expr {
>                     kind: ExprKind::Error,
>                     range: start..end,
>                 }
>             }))),
>             range: input.to_range().start..remaining.to_range().start,
>         },
>     ))
> }
> ```

Ah, thanks for the help! Although I have used Nom before, I’ve always used it in a more imperative manner – I haven’t used `preceded`, `terminated`, `all_consuming`, `alt`, `map` or `pair` before. I think I might take a look through `nom::combinators` though, as they seem very useful.

Also, I just realised that `paren()` would have to return multiple `Expr`s. Let me explain:

I would like every bit of Rust’s syntax (including parentheses) to get its own highlighting, that can later be ‘linked’ to variants of `HighlightGroup` (e.g. `Delimiter` for parentheses). This implies that parentheses would get their own entries in the now inaccurately-named `Expr` enum. It also implies that `Ident` has no need to store its contents anymore.

So, `paren()` would have to return a `Paren`, the contained expression, and finally another `Paren`.

> In regards to the `todo!()` you placed for the `take(0usize)` error, the correct value is always `0..0`. This is because, when given this expression:
> 
> ```rust
> alt((
>     expr,
>     map(take(0usize), |_| Expr {
>         kind: ExprKind::Error,
>         range: 0..0,
>     }),
> ))
> ```
> 
> The only way for the `expr()` parser to fail above is if the input string is `""`, meaning that the fallback error range must always be `0..0`.

Ah, I was wondering what that part was for. Now that I’ve looked at it more closely though, it makes more sense. Do you think it would be easier to show that behaviour through a simple

```rust
if input.fragment() == "" {
    ...
}
```

though?

> As a result of the above changes, I can get the following outputs from the parser example:
> 
> ```
> foo     Expr { kind: Ident("foo"), range: 0..3 }
> (foo)   Expr { kind: Paren(Expr { kind: Ident("foo"), range: 1..4 }), range: 0..5 }
> (foo))  Expr { kind: Paren(Expr { kind: Ident("foo"), range: 1..4 }), range: 0..5 }
> (%      Expr { kind: Paren(Expr { kind: Error, range: 1..2 }), range: 0..2 }
> (       Expr { kind: Paren(Expr { kind: Error, range: 1..1 }), range: 0..1 }
> %       Expr { kind: Error, range: 0..1 }
> ()      Expr { kind: Paren(Expr { kind: Error, range: 1..1 }), range: 0..2 }
>         Expr { kind: Error, range: 0..0 }
> ```

These results look just like what I’m looking for, apart from `(foo))`. Any idea why that isn’t reported as an error in any way?

> Hope my responses helped in some way! Did I answer all your questions?

Yes, this was very helpful. I do have a question, though:

Do you think that unclosed parentheses should be highlighted as an error? Or, more generally, do you think that cases that are both incorrect syntactically (e.g. unclosed parenthesis) and often reached for longer periods of time while typing (e.g. if you’re writing out a long function call and aren’t using auto-closing brackets) should be highlighted as errors? Or should the syntax highlighter minimise highlighting things as errors if that specific case is common? A good example is if you’re typing something in parentheses: should from the first parenthesis to the end of the document be highlighted as an error until the closing parenthesis is typed? Or should the highlighter do its best and attempt to continue making out an expression? (Surely the rest of the document contains more than one expression, though. So if parentheses are only allowed to contain a single expression, will only a single expression be highlighted until the error highlighting kicks in?) An example of a nice use of error highlighting can be seen [here](https://user-images.githubusercontent.com/797170/76173969-0bdc4980-619c-11ea-9f24-7899e2722910.gif), where error highlighting is visible when the author is adding an entry to the `Theme` struct, as well as when they are adding a function to `Theme`’s `impl` block.

Sorry for all the questions 😊

**Comment by ebkalderon** [comment]
> So are you saying that `LocatedSpan` is character-based? When you say that you would recommend a token-based input type, would that mean lexing the input first, before passing it into the parser? If so, would you say that this is worth it for syntax highlighting, or, since lexing covers the majority of work a syntax highlighter has to do, it would be mostly unnecessary?

Yes, `LocatedSpan<&str>` is character-based, and `LocatedSpan<&[u8]>` is byte-based.

And yes, I would personally recommend using a lexer first and then turning the resulting stream of tokens into a `nom`-compatible type for use in the parser. For a simple syntax highlighter, you could get by with just a lexer alone. The lexer would break down the text into a stream of tokens with associated span information, and then colors would then be associated with specific tokens such as keywords, delimiters, and punctuation. However, you would still need to build a parser of some kind to perform semantic analysis on the resulting token stream if you want to do anything more advanced than this, e.g. coloring function and struct identifiers differently than variable identifiers, for example.

> Ah, thanks for the help! Although I have used Nom before, I’ve always used it in a more imperative manner – I haven’t used `preceded`, `terminated`, `all_consuming`, `alt`, `map` or `pair` before. I think I might take a look through `nom::combinators` though, as they seem very useful.
> \<snip\>

It sounds to me like you need your parser to produce a concrete syntax tree (CST) like [`rowan`](https://github.com/rust-analyzer/rowan) instead of an AST. A concrete syntax tree preserves the original lexical tokens which make up the nodes in the tree. For example, you might have `ExprKind::Paren` node contain an `ExprKind::Expr` node, but it would also contain a leading `(` token and a trailing `)` token.

I'd recommend you read up on the [Roslyn Compiler Architecture](https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#syntax-trees) for more information on the theory of lossless syntax trees, or maybe just take a look at how `rowan` and `rust-analyzer` process text for parsing, type checking, highlighting, etc. I'd also recommend that you learn more about `nom` and parser combinators in general. You would be surprised what feats they are capable of. 😄 

It should be possible to construct a `rowan` syntax tree from within `nom`, just like it's possible to construct an AST or anything else within `nom`, but the process is lengthy enough to describe that I probably would not be able to fit it in a GitHub comment, haha. It would be better serving of a series of blog posts or maybe a YouTube video to break down how all of this works.

> Ah, I was wondering what that part was for. Now that I’ve looked at it more closely though, it makes more sense. Do you think it would be easier to show that behaviour through a simple
> 
> ```rust
> if input.fragment() == "" {
>     ...
> }
> ```
> 
> though?

Sure, but then it wouldn't match the equivalent PEG definition, which was the original point behind my blog post. 😄 Also, it wouldn't usable with the `terminated()` expression below it. The fact that this check is occurring inside of a combinator is critical because performing the check outside, like you suggest, would not execute the `"expected EOF"` error handling before returning from the function.

> These results look just like what I’m looking for, apart from `(foo))`. Any idea why that isn’t reported as an error in any way?

It is an error. You aren't printing the errors in your example and are discarding them immediately once the parsing completes. Instead of returning a `(Expr, Vec<Error>)`, like the blog post had described, you are returning only the `Expr` instead and are throwing the errors away.

Remember that the `Expr` represents the parser's understanding of the input text provided. It successfully parsed `(foo))` as a `Paren(...)` expression, and it emitted an error message that there was an extra `)` in the text, but this error was not returned and printed in your example. The parser is working as intended.

Changing the `parse()` function to return an `(Expr, Vec<Error>)` and to print the accumulated errors, I see the following output locally:

```text
foo     Expr { kind: Ident("foo"), range: 0..3 }                                     []
(foo)   Expr { kind: Paren(Expr { kind: Ident("foo"), range: 1..4 }), range: 0..5 }  []
(foo))  Expr { kind: Paren(Expr { kind: Ident("foo"), range: 1..4 }), range: 0..5 }  [Error(5..6, "expected EOF")]
(%      Expr { kind: Paren(Expr { kind: Error, range: 1..2 }), range: 0..2 }         [Error(1..2, "unexpected `%`"), Error(2..2, "missing `)`")]
(       Expr { kind: Paren(Expr { kind: Error, range: 1..1 }), range: 0..1 }         [Error(1..1, "expected expression after `(`"), Error(1..1, "missing `)`")]
%       Expr { kind: Error, range: 0..1 }                                            [Error(0..1, "unexpected `%`")]
()      Expr { kind: Paren(Expr { kind: Error, range: 1..1 }), range: 0..2 }         [Error(1..2, "expected expression after `(`")]
        Expr { kind: Error, range: 0..0 }                                            []
```

> Do you think that unclosed parentheses should be highlighted as an error? Or, more generally, do you think that cases that are both incorrect syntactically (e.g. unclosed parenthesis) and often reached for longer periods of time while typing (e.g. if you’re writing out a long function call and aren’t using auto-closing brackets) should be highlighted as errors?

That would be for you to decide, I think. 😉 It would depend both on the language being lexed and/or parsed and also on the grammatical context the parser is currently in. If we take Rust as an example, an unclosed parentheses would not affect the syntax highlighting of an `fn` keyword halfway down the page. However, an unclosed double-quote from within a string literal would definitely highlight the rest of the text yellow.

This is where having a token stream and concrete syntax tree would be of huge help. Being able to traverse the nodes in the tree would be able to identify compound structures in the text, e.g. functions, structs, `impl` blocks, and macro definitions, but having each node also contain the original tokens it parsed from would allow for the highlighting of keywords, punctuation, delimiters, literals, etc. If you decide to deem unclosed parentheses as an error, you would then check to see if the `Paren` expression ends with more than one `)` token, which would result in a different color choice.

**Comment by lunacookies** [comment]
> And yes, I would personally recommend using a lexer first and then turning the resulting stream of tokens into a `nom`-compatible type for use in the parser.

Do you think that this lexer could also be implemented with Nom, or do you think there are better choices out there?

> For a simple syntax highlighter, you could get by with just a lexer alone. The lexer would break down the text into a stream of tokens with associated span information, and then colors would then be associated with specific tokens such as keywords, delimiters, and punctuation. However, you would still need to build a parser of some kind to perform semantic analysis on the resulting token stream if you want to do anything more advanced than this, e.g. coloring function and struct identifiers differently than variable identifiers, for example.

Thanks for this, that makes a lot of sense.

> It sounds to me like you need your parser to produce a concrete syntax tree (CST) like [`rowan`](https://github.com/rust-analyzer/rowan) instead of an AST. A concrete syntax tree preserves the original lexical tokens which make up the nodes in the tree. For example, you might have `ExprKind::Paren` node contain an `ExprKind::Expr` node, but it would also contain a leading `(` token and a trailing `)` token.
> 
> I'd recommend you read up on the [Roslyn Compiler Architecture](https://github.com/dotnet/roslyn/wiki/Roslyn%20Overview#syntax-trees) for more information on the theory of lossless syntax trees, or maybe just take a look at how `rowan` and `rust-analyzer` process text for parsing, type checking, highlighting, etc.

I’ll look into that, it sounds promising.

> I'd also recommend that you learn more about `nom` and parser combinators in general. You would be surprised what feats they are capable of. 😄

This is definitely something I’ll do :)

> It should be possible to construct a `rowan` syntax tree from within `nom`, just like it's possible to construct an AST or anything else within `nom`, but the process is lengthy enough to describe that I probably would not be able to fit it in a GitHub comment, haha. It would be better serving of a series of blog posts or maybe a YouTube video to break down how all of this works.

I would definitely watch/read that if you or someone else makes it, but don’t feel pressured or anything 😊

> Sure, but then it wouldn't match the equivalent PEG definition, which was the original point behind my blog post. 😄 Also, it wouldn't usable with the `terminated()` expression below it. The fact that this check is occurring inside of a combinator is critical because performing the check outside, like you suggest, would not execute the `"expected EOF"` error handling before returning from the function.

Thanks for the explanation.

> It is an error. You aren't printing the errors in your example and are discarding them immediately once the parsing completes. Instead of returning a `(Expr, Vec<Error>)`, like the blog post had described, you are returning only the `Expr` instead and are throwing the errors away.

Ah, of course.

> That would be for you to decide, I think. 😉 It would depend both on the language being lexed and/or parsed and also on the grammatical context the parser is currently in. If we take Rust as an example, an unclosed parentheses would not affect the syntax highlighting of an `fn` keyword halfway down the page. However, an unclosed double-quote from within a string literal would definitely highlight the rest of the text yellow.
> 
> This is where having a token stream and concrete syntax tree would be of huge help. Being able to traverse the nodes in the tree would be able to identify compound structures in the text, e.g. functions, structs, `impl` blocks, and macro definitions, but having each node also contain the original tokens it parsed from would allow for the highlighting of keywords, punctuation, delimiters, literals, etc. If you decide to deem unclosed parentheses as an error, you would then check to see if the `Paren` expression ends with more than one `)` token, which would result in a different color choice.

This definitely sounds useful. I think I’ll play around with a few different methodologies and see what works best. Thanks for all your help! :)

**Comment by ebkalderon** [comment]
> Do you think that this lexer could also be implemented with Nom, or do you think there are better choices out there?

Sure! Here's a `nom` based lexer I wrote which uses `LocatedSpan` internally to produce a lazy iterator of tokens: [ebkalderon/nix-language-server](https://github.com/ebkalderon/nix-language-server/tree/master/nix-lexer). It works very well and it's quite fast! Another promising project you could check out is [logos](https://github.com/maciejhirsz/logos), a derive macro which aims to generate fast and efficient lookup table based lexers at compile time. It hasn't been able to fully accommodate my projects' specific needs yet, but the most recent release looks really promising. I might try it again sometime. :smile:

> I would definitely watch/read that if you or someone else makes it, but don’t feel pressured or anything 😊

Sure, no worries! Maybe I'll write a follow-up blog post someday on the topic, haha.

> This definitely sounds useful. I think I’ll play around with a few different methodologies and see what works best. Thanks for all your help! :)

Anytime! Thank you for all the thought-provoking questions. I haven't really thought about syntax highlighting with fault-tolerant parsers before (I've only really considered syntax checking, semantic analysis, type checking, formatting, and auto-completion), but I think it should work just as well.

Wishing you all the best in your future projects, @arzg! :heart:
